name: recipes
description: Recipe Finder

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.2
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  flutter_slidable: ^2.0.0
  platform: ^3.1.0
  flutter_svg: ^1.1.4
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  chopper: ^4.0.6
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  chopper_generator: ^4.0.6

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
