name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/